### ISSUE TITLE
Cannot open PDF file after open wrong file

### ISSUE THREAD

**Issue by codingjeremy** [android/graphics-samples#23]
<a href="https://github.com/luongdolong"><img src="https://avatars3.githubusercontent.com/u/3131103?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [luongdolong](https://github.com/luongdolong)**
_Thursday May 24, 2018 at 03:57 GMT_
_Originally opened as https://github.com/googlesamples/android-PdfRendererBasic/issues/25_

----

I have a file: pdf.txt. I rename it to: pdf.pdf
Below is my steps:
1. Open app. Open file "sample.pdf". -> OK
2. Open file "pdf.pdf" -> show Toast: "Error! file not in PDF format or corrupted"
3. Open file "sample.pdf" again. -> show Toast: "Error! file not in PDF format or corrupted"
Now I cannot open PDF file. 
If I kill app, and open app again. File "sample.pdf" show ok. And if I open wrong file. I cannot open any files more.
How can I resolve this issue? Thank you

**Comment by codingjeremy** [comment]
<a href="https://github.com/msamyatl"><img src="https://avatars1.githubusercontent.com/u/37280232?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [msamyatl](https://github.com/msamyatl)**
_Wednesday Jun 20, 2018 at 03:14 GMT_

----

@luongdolong same problem here. were you able to solve it?

**Comment by codingjeremy** [comment]
<a href="https://github.com/wywy4pm"><img src="https://avatars3.githubusercontent.com/u/10074663?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [wywy4pm](https://github.com/wywy4pm)**
_Wednesday Oct 17, 2018 at 08:34 GMT_

----

the same problem.

**Comment by codingjeremy** [comment]
<a href="https://github.com/antonkovalyov351"><img src="https://avatars0.githubusercontent.com/u/11294259?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [antonkovalyov351](https://github.com/antonkovalyov351)**
_Thursday Dec 20, 2018 at 09:05 GMT_

----

+1

**Comment by codingjeremy** [comment]
<a href="https://github.com/AswinpAshok"><img src="https://avatars3.githubusercontent.com/u/25843394?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [AswinpAshok](https://github.com/AswinpAshok)**
_Tuesday Dec 25, 2018 at 14:45 GMT_

----

Same issue. Any solutions?

**Comment by codingjeremy** [comment]
<a href="https://github.com/antonkovalyov351"><img src="https://avatars0.githubusercontent.com/u/11294259?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [antonkovalyov351](https://github.com/antonkovalyov351)**
_Tuesday Dec 25, 2018 at 14:55 GMT_

----

I used [PdfiumAndroid](https://github.com/barteksc/PdfiumAndroid) library instead of default `PdfRenderer`.
It doesn't have this issue.

**Comment by codingjeremy** [comment]
<a href="https://github.com/dikadk"><img src="https://avatars1.githubusercontent.com/u/15266737?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dikadk](https://github.com/dikadk)**
_Wednesday Jan 09, 2019 at 19:10 GMT_

----

+1

**Comment by codingjeremy** [comment]
<a href="https://github.com/dbland87"><img src="https://avatars0.githubusercontent.com/u/17143204?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dbland87](https://github.com/dbland87)**
_Tuesday Apr 02, 2019 at 20:08 GMT_

----

+1 
Has anyone found a good workaround for this?

**Comment by codingjeremy** [comment]
<a href="https://github.com/mnxamdev"><img src="https://avatars2.githubusercontent.com/u/46384868?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mnxamdev](https://github.com/mnxamdev)**
_Wednesday May 22, 2019 at 19:44 GMT_

----

This is a pretty serious issue. Seems like the ParcelFileDescriptor that is used as a constructor parameter is being held onto somehow and it keeps getting used instead of any new ones that are passed into any new instances of the PdfRenderer object. I would like to not have to use a third party library to display PDFs in my app.

**Comment by codingjeremy** [comment]
<a href="https://github.com/msamyatl"><img src="https://avatars1.githubusercontent.com/u/37280232?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [msamyatl](https://github.com/msamyatl)**
_Wednesday May 22, 2019 at 23:45 GMT_

----

@mnxamdev the problem was fixed in android 28: https://issuetracker.google.com/issues/37052344

**Comment by codingjeremy** [comment]
<a href="https://github.com/mnxamdev"><img src="https://avatars2.githubusercontent.com/u/46384868?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mnxamdev](https://github.com/mnxamdev)**
_Friday May 31, 2019 at 20:36 GMT_

----

> @mnxamdev the problem was fixed in android 28: https://issuetracker.google.com/issues/37052344

Thanks for the information, good to know. How can this be only fixed in Android 9??? What about the thousands of customers that we have that aren't on Android 9??? Is there some sort of work around which we can implement? Is there a way we can just get the PDF bytes and open that way?

**Comment by codingjeremy** [comment]
<a href="https://github.com/msamyatl"><img src="https://avatars1.githubusercontent.com/u/37280232?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [msamyatl](https://github.com/msamyatl)**
_Sunday Jun 02, 2019 at 21:40 GMT_

----

Your best best is to probably use another pdf library to detect
password-protected files.

**Comment by codingjeremy** [comment]
<a href="https://github.com/pgaikwad-os"><img src="https://avatars2.githubusercontent.com/u/50235966?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [pgaikwad-os](https://github.com/pgaikwad-os)**
_Thursday Aug 22, 2019 at 09:44 GMT_

----

Still facing this issue in API-28  and API-29.

**Stacktrace** :
```
_2019-08-22 14:52:54.297 31420-31431/com.myandroid.app.debug E/System: Uncaught exception thrown by finalizer
2019-08-22 14:52:54.353 31420-31431/com.myandroid.app.debug E/System: java.io.IOException: file not in PDF format or corrupted
        at android.graphics.pdf.PdfRenderer.nativeClose(Native Method)
        at android.graphics.pdf.PdfRenderer.doClose(PdfRenderer.java:250)
        at android.graphics.pdf.PdfRenderer.finalize(PdfRenderer.java:238)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:250)
        at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:237)
        at java.lang.Daemons$Daemon.run(Daemons.java:103)
        at java.lang.Thread.run(Thread.java:764)_

```
Device Information: Pixel C - v8.1.0

Other links referred:
https://github.com/voghDev/PdfViewPager/issues/101 >> https://github.com/voghDev/PdfViewPager/issues/101#issuecomment-452819867
https://issuetracker.google.com/issues/37052344


**Any solution?**

**Comment by antoniogonzalezs** [comment]
This is still happening with android Api 27. Any fix or workaround? 

Edit: A workaround I implemented is to check first whether the file is a valid PDF by checking the file magic number: https://en.wikipedia.org/wiki/List_of_file_signatures
