### ISSUE TITLE
DrawableTinting sample keeps crashing

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [android/graphics-samples#30]
![image](https://user-images.githubusercontent.com/5357526/65394928-35471b80-dd9c-11e9-8404-e4323aaaa526.png)

2019-09-23 00:51:17.383 24339-24339/? E/drawabletintin: Unknown bits set in runtime_flags: 0x8000
2019-09-23 00:51:17.605 24339-24339/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.android.drawabletinting, PID: 24339
    java.util.UnknownFormatConversionException: Conversion = 'End of String'
        at java.util.Formatter$FormatSpecifierParser.peek(Formatter.java:2642)
        at java.util.Formatter$FormatSpecifierParser.<init>(Formatter.java:2603)
        at java.util.Formatter.parse(Formatter.java:2558)
        at java.util.Formatter.format(Formatter.java:2505)
        at java.util.Formatter.format(Formatter.java:2459)
        at java.lang.String.format(String.java:2911)
        at android.content.res.Resources.getString(Resources.java:485)
        at android.support.v4.app.Fragment.getString(Fragment.java:795)
        at com.example.android.drawabletinting.DrawableTintingFragment.updateTint(DrawableTintingFragment.java:272)
        at com.example.android.drawabletinting.DrawableTintingFragment.onCreateView(DrawableTintingFragment.java:209)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2439)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3273)
        at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229)
        at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:620)
        at com.example.android.common.activities.SampleActivityBase.onStart(SampleActivityBase.java:39)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1432)
        at android.app.Activity.performStart(Activity.java:7825)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3294)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by yaraki** [comment]
Fixed in #33.

**Comment by AndroidDeveloperLB** [comment]
Confirmed.
Can you please explain why it crashed?
